# Generated by Django 4.1.7 on 2023-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
    ]
