# Generated by Django 4.1.7 on 2023-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='conver',
            field=models.ImageField(default='', upload_to='gallery/%Y/%m/', verbose_name='imagem'),
        ),
    ]
