# Generated by Django 4.1.7 on 2023-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eletro', 'eletro'), ('musculação', 'musculação')], max_length=50)),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
