# Generated by Django 4.1.3 on 2023-07-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
