from django.urls import path
from . import views

app_name: str = 'author'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('login/login_create/', views.login_create, name='login_create'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/settings/socialnetwork/edit/',
         views.settings_socialnetwork,
         name='socialnetwork',
         ),
    path('dashboard/settings/sectionintro/edit/',
         views.settings_sectionintro,
         name='sectionintro',
         ),
    path('dashboard/settings/profile/edit/',
         views.settings_profile,
         name='profile',
         ),
    path('dashboard/settings/initial-gallery/edit/',
         views.settings_initial_gallery,
         name='initialgallery',
         ),
    path('dashboard/settings/services/',
         views.ServiceView.all_services,
         name='services',
         ),
    path('dashboard/settings/services/<int:id>/edit/',
         views.ServiceView.as_view(),
         name='service_edit',
         ),
    path('dashboard/settings/services/new/',
         views.ServiceView.as_view(),
         name='new_service',
         ),
    path('dashboard/settings/services/delete/<int:id>/',
         views.ServiceDeleteView.as_view(),
         name='service_delete',
         ),
    path('dashboard/settings/adress/',
         views.settings_adress,
         name='adress',
         ),
    path('dashboard/gallery/',
         views.GalleryImageView.all_images,
         name='gallery'),
    path('dashboard/gallery/<int:id>/edit/',
         views.GalleryImageView.as_view(),
         name='gallery_edit'),
    path('dashboard/gallery/new/',
         views.GalleryImageView.as_view(),
         name='new_image'),
    path('dashboard/gallery/delete/<int:id>/',
         views.GalleryDeleteView.as_view(),
         name='image_delete',
         ),
]
