# Generated by Django 4.1.7 on 2023-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.CharField(default='', max_length=255, verbose_name='link do instagram')),
                ('facebook_link', models.CharField(default='', max_length=255, verbose_name='link do facebook')),
                ('whatsapp_link', models.CharField(default='', max_length=255, verbose_name='link do whatsapp')),
                ('instagram_text', models.CharField(max_length=255, verbose_name='texto para o instagram')),
                ('facebook_text', models.CharField(max_length=255, verbose_name='texto para o facebook')),
                ('whatsapp_phone', models.CharField(max_length=255, verbose_name='número do whatsapp')),
            ],
        ),
    ]
