# Generated by Django 4.1.7 on 2023-03-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='nome do estabelecimento')),
                ('adress', models.CharField(default='', max_length=255, verbose_name='endereço')),
                ('city', models.CharField(default='', max_length=255, verbose_name='bairro e cidade')),
                ('postal', models.CharField(default='', max_length=255, verbose_name='cep')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereço',
            },
        ),
        migrations.CreateModel(
            name='PreGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='título')),
                ('description', models.TextField(default='', max_length=500, verbose_name='descrição')),
                ('image_one', models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='primeira imagem')),
                ('image_two', models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='segunda imagem')),
                ('image_three', models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='terceira imagem')),
            ],
            options={
                'verbose_name': 'Galeria de imagens da home',
                'verbose_name_plural': 'Galeria de imagens da home',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='título')),
                ('description', models.TextField(default='', max_length=500, verbose_name='descrição')),
                ('image', models.ImageField(blank=True, default='', upload_to='app_home/images/profile/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Perfil do Profissional',
                'verbose_name_plural': 'Perfil do Profissional',
            },
        ),
        migrations.CreateModel(
            name='SectionIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Título')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Descrição')),
                ('subtitle_one', models.CharField(default='', max_length=255, verbose_name='Primeiro Subtítulo')),
                ('sub_description_one', models.TextField(default='', max_length=255, verbose_name='Primeira descrição')),
                ('subtitle_two', models.CharField(default='', max_length=255, verbose_name='Segundo Subtítulo')),
                ('sub_description_two', models.TextField(default='', max_length=255, verbose_name='Segunda descrição')),
                ('subtitle_three', models.CharField(default='', max_length=255, verbose_name='Terceiro Subtítulo')),
                ('sub_description_three', models.TextField(default='', max_length=255, verbose_name='Terceira descrição')),
            ],
            options={
                'verbose_name': 'Seção de introdução',
                'verbose_name_plural': 'Seção de introdução',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='título')),
                ('description', models.TextField(default='', max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Serviços',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.CharField(default='', max_length=255, verbose_name='link do instagram')),
                ('facebook_link', models.CharField(default='', max_length=255, verbose_name='link do facebook')),
                ('whatsapp_link', models.CharField(default='', max_length=255, verbose_name='link do whatsapp')),
                ('instagram_text', models.CharField(max_length=255, verbose_name='texto para o botão do instagram')),
                ('facebook_text', models.CharField(max_length=255, verbose_name='texto para o botão do facebook')),
                ('whatsapp_phone', models.CharField(max_length=255, verbose_name='número do whatsapp')),
            ],
            options={
                'verbose_name': 'Redes Sociais',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.adress', verbose_name='endereço')),
                ('pre_gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.pregallery', verbose_name='galeria de imagens')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.profile', verbose_name='perfil do profissional')),
                ('section_intro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.sectionintro', verbose_name='seção intro')),
                ('services', models.ManyToManyField(to='app_home.service', verbose_name='serviços')),
                ('social_network', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.socialnetwork', verbose_name='redes sociais')),
            ],
            options={
                'verbose_name': 'Todas as configurações do site',
                'verbose_name_plural': 'Todas as configurações do site',
            },
        ),
    ]
