# Generated by Django 4.1.7 on 2023-03-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='is_home',
            field=models.BooleanField(default=True, verbose_name='is_home'),
        ),
    ]
