# Generated by Django 4.1.7 on 2023-02-28 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('adress', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('postal', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
                ('image_one', models.ImageField(default='', upload_to='app_home/images/pre-gallery')),
                ('image_two', models.ImageField(default='', upload_to='app_home/images/pre-gallery')),
                ('image_three', models.ImageField(default='', upload_to='app_home/images/pre-gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SectionIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Título da seção inicial')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Descrição da seção intro')),
                ('subtitle_one', models.CharField(default='', max_length=255, verbose_name='Primeiro Subtítulo')),
                ('sub_description_one', models.TextField(default='', max_length=255, verbose_name='Primeira descrição')),
                ('subtitle_two', models.CharField(default='', max_length=255, verbose_name='Segundo Subtítulo')),
                ('sub_description_two', models.TextField(default='', max_length=255, verbose_name='Segunda descrição')),
                ('subtitle_three', models.CharField(default='', max_length=255, verbose_name='Terceiro Subtítulo')),
                ('sub_description_three', models.TextField(default='', max_length=255, verbose_name='Terceira descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.CharField(default='', max_length=255, verbose_name='link do instagram')),
                ('facebook_link', models.CharField(default='', max_length=255, verbose_name='link do facebook')),
                ('whatsapp_link', models.CharField(default='', max_length=255, verbose_name='link do whatsapp')),
                ('instagram_text', models.CharField(max_length=255, verbose_name='texto para o instagram')),
                ('facebook_text', models.CharField(max_length=255, verbose_name='texto para o facebook')),
                ('whatsapp_phone', models.CharField(max_length=255, verbose_name='número do whatsapp')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='description_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='instagram_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='sub_description_one_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='sub_description_three_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='sub_description_two_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='subtitle_one_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='subtitle_three_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='subtitle_two_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title_section_intro',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='whatsapp_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_description',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='descrição do perfil'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='adress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.adress'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='pre_gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.pregallery'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='section_intro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.sectionintro'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='services',
            field=models.ManyToManyField(to='app_home.service'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='social_network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.socialnetwork'),
        ),
    ]
