# Generated by Django 4.1.7 on 2023-02-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeContact',
            new_name='HomeContent',
        ),
    ]
