# Generated by Django 4.1.7 on 2023-03-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_homecontent_is_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='is_home',
        ),
    ]
