# Generated by Django 4.1.7 on 2023-02-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_adress_pregallery_sectionintro_service_socialnetwork_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Todas as configurações do site', 'verbose_name_plural': 'Todas as configurações do site'},
        ),
        migrations.AlterModelOptions(
            name='pregallery',
            options={'verbose_name': 'Galeria de imagens da home', 'verbose_name_plural': 'Galeria de imagens da home'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil do Profissional', 'verbose_name_plural': 'Perfil do Profissional'},
        ),
        migrations.AlterModelOptions(
            name='sectionintro',
            options={'verbose_name': 'Seção de introdução', 'verbose_name_plural': 'Seção de introdução'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviços', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Redes Sociais', 'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress',
            field=models.CharField(default='', max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='bairro e cidade'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='nome do estabelecimento'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal',
            field=models.CharField(default='', max_length=255, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='adress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.adress', verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='pre_gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.pregallery', verbose_name='galeria de imagens'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.profile', verbose_name='perfil do profissional'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='section_intro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.sectionintro', verbose_name='seção intro'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='services',
            field=models.ManyToManyField(to='app_home.service', verbose_name='serviços'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='social_network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_home.socialnetwork', verbose_name='redes sociais'),
        ),
        migrations.AlterField(
            model_name='pregallery',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='pregallery',
            name='image_one',
            field=models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='primeira imagem'),
        ),
        migrations.AlterField(
            model_name='pregallery',
            name='image_three',
            field=models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='terceira imagem'),
        ),
        migrations.AlterField(
            model_name='pregallery',
            name='image_two',
            field=models.ImageField(default='', upload_to='app_home/images/pre-gallery', verbose_name='segunda imagem'),
        ),
        migrations.AlterField(
            model_name='pregallery',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='app_home/images/profile/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='sectionintro',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sectionintro',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook_text',
            field=models.CharField(max_length=255, verbose_name='texto para o botão do facebook'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='instagram_text',
            field=models.CharField(max_length=255, verbose_name='texto para o botão do instagram'),
        ),
    ]
