# Generated by Django 4.1.7 on 2023-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_rename_homecontact_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='description_section_intro',
            field=models.TextField(default='', max_length=255, verbose_name='Descrição da seção intro'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='sub_description_one_section_intro',
            field=models.TextField(default='', max_length=255, verbose_name='Primeira descrição'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='sub_description_three_section_intro',
            field=models.TextField(default='', max_length=255, verbose_name='Terceira descrição'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='sub_description_two_section_intro',
            field=models.TextField(default='', max_length=255, verbose_name='Segunda descrição'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='subtitle_one_section_intro',
            field=models.CharField(default='', max_length=255, verbose_name='Primeiro Subtítulo'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='subtitle_three_section_intro',
            field=models.CharField(default='', max_length=255, verbose_name='Terceiro Subtítulo'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='subtitle_two_section_intro',
            field=models.CharField(default='', max_length=255, verbose_name='Segundo Subtítulo'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_section_intro',
            field=models.CharField(default='', max_length=255, verbose_name='Título da seção inicial'),
        ),
    ]
