# Generated by Django 4.1.7 on 2023-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_adress_options_alter_homecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook_text',
            field=models.CharField(max_length=255, verbose_name='texto para o botãodo facebook'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='instagram_text',
            field=models.CharField(max_length=255, verbose_name='texto para o botãodo instagram'),
        ),
    ]
