# Generated by Django 4.1.7 on 2023-04-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_menucontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook_link',
            field=models.CharField(max_length=255, verbose_name='link do facebook'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='instagram_link',
            field=models.CharField(max_length=255, verbose_name='link do instagram'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='whatsapp_link',
            field=models.CharField(max_length=255, verbose_name='link do whatsapp'),
        ),
    ]
